In [ ]:
import pandas as pd
import numpy as np

In [12]:
df = pd.read_csv("/content/sample_data/Logistic_Regression_Dataset_Students.csv",names=["x1","x2","y"])

In [13]:
df

x1         x2  y
0   34.623660  78.024693  0
1   30.286711  43.894998  0
2   35.847409  72.902198  0
3   60.182599  86.308552  1
4   79.032736  75.344376  1
..        ...        ... ..
95  83.489163  48.380286  1
96  42.261701  87.103851  1
97  99.315009  68.775409  1
98  55.340018  64.931938  1
99  74.775893  89.529813  1

[100 rows x 3 columns]

In [18]:
x = df.iloc[:,[0,1]].values
y = df.iloc[:,2].values

In [19]:
x

array([[34.62365962, 78.02469282],
       [30.28671077, 43.89499752],
       [35.84740877, 72.90219803],
       [60.18259939, 86.3085521 ],
       [79.03273605, 75.34437644],
       [45.08327748, 56.31637178],
       [61.10666454, 96.51142588],
       [75.02474557, 46.55401354],
       [76.0987867 , 87.42056972],
       [84.43281996, 43.53339331],
       [95.86155507, 38.22527806],
       [75.01365839, 30.60326323],
       [82.30705337, 76.4819633 ],
       [69.36458876, 97.71869196],
       [39.53833914, 76.03681085],
       [53.97105215, 89.20735014],
       [69.07014406, 52.74046973],
       [67.94685548, 46.67857411],
       [70.66150955, 92.92713789],
       [76.97878373, 47.57596365],
       [67.37202755, 42.83843832],
       [89.67677575, 65.79936593],
       [50.53478829, 48.85581153],
       [34.21206098, 44.2095286 ],
       [77.92409145, 68.97235999],
       [62.27101367, 69.95445795],
       [80.19018075, 44.82162893],
       [93.1143888 , 38.80067034],
       [61.83020602,

In [20]:
y

array([0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1])

In [21]:
# we need to preprocess the data
b0 = 0.0
b1 = 0.0
b2 = 0.0
from sklearn import preprocessing
xp = preprocessing.scale(x)

In [22]:
# we need to have train,testand split as well has we need to have kfold to split into different folds
from sklearn.model_selection import KFold,train_test_split

kf = KFold(n_splits=5)

In [23]:
for train_index,test_index in kf.split(xp):
  xtrain,xtest,ytrain,ytest = train_test_split(xp,y,test_size=0.20,random_state=0)
  x1 = xtrain[:,0]
  x2 = xtrain[:,1]
  b0 = 0.0
  b1 = 0.0
  b2 = 0.0
  epoch = 10000
  alpha = 0.001
  while(epoch > 0):
    for i in range(len(xtrain)):
      pred = 1/(1+np.exp(-(b0+(b1*x1[i])+(b2*x2[i]))))
      b0 = b0 + alpha*(ytrain[i] - pred)*(pred)*(1-pred)*1.0
      b1 = b1 + alpha*(ytrain[i] - pred)*(pred)*(1-pred)*x1[i]
      b2 = b2 + alpha*(ytrain[i] - pred)*(pred)*(1-pred)*x2[i]
    epoch = epoch -1
  print(b0)
  print(b1)
  print(b2)

0.9875270298732239
2.6698848778906488
2.7274062957733913
0.9875270298732239
2.6698848778906488
2.7274062957733913
0.9875270298732239
2.6698848778906488
2.7274062957733913
0.9875270298732239
2.6698848778906488
2.7274062957733913
0.9875270298732239
2.6698848778906488
2.7274062957733913


In [24]:
print(b0)
print(b1)
print(b2)

0.9875270298732239
2.6698848778906488
2.7274062957733913


In [25]:
final_pred = []
x3 = xtest[:,0]
x4 = xtest[:,1]
print(ytest)

[1 0 0 0 1 1 1 1 0 1 0 0 0 1 1 1 0 1 1 1]


In [27]:
y_pred = [0]*len(xtest)
y_pred

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [28]:
for i in range(len(xtest)):
  y_pred[i] = np.round(1/1+np.exp(-(b0+(b1*x3[i])+(b2*x4[i]))))
  final_pred.append(np.ceil(y_pred[i]))
print(final_pred)

[2.0, 2.0, 9.0, 10.0, 1.0, 1.0, 3.0, 1.0, 36.0, 1.0, 65.0, 140.0, 26.0, 1.0, 3.0, 1.0, 40.0, 1.0, 3.0, 1.0]


In [29]:
from sklearn.metrics import accuracy_score

print("accuracy : ",accuracy_score(ytest,y_pred))

accuracy :  0.4
